server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    root: warn
    com.keepory: info
